### ISSUE TITLE
Cannot upload image over udp to mcumgr zephyr sample

### ISSUE THREAD

**Issue by nicovince** [apache/mynewt-mcumgr-cli#17]
Hello, 

I'm working with a nucleo f429zi and I'm trying to setup the [sample](https://docs.zephyrproject.org/latest/samples/subsys) provided by Zephyr to get mcumgr working.
I compiled the firmware for UDP connection:
```
west build -p auto -b nucleo_f429zi -d build_f429/smpsvr zephyr/samples/subsys/mgmt/mcumgr/smp_svr/ -- -DOVERLAY_CONFIG=overlay-udp.conf
```

I'm using go1.15.3, I downloaded mcumgr through `go get github.com/apache/mynewt-mcumgr-cli/mcumgr`.

mcumgr manages to list the images available on the target: 
```bash
~/go/bin/mcumgr --conntype udp --connstring=[192.168.1.1]:1337 image list
Images:
 image=0 slot=0
    version: 0.0.0
    bootable: true
    flags: active confirmed
    hash: 88f4caa07e1391eb592261e185d2f7cc1d235ab3860e0749e3f602243207ed55
Split status: N/A (0)
```

Unfortunately an upload operation fails:
```bash
~/go/bin/mcumgr --conntype udp --connstring=[192.168.1.1]:1337 image upload build_f429/smpsvr/zephyr/zephyr.signed.bin   
 0 / 90644 [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%
Error: ImageUpload unexpected error after 0/90644 bytes
```

with -ldebug option, I get the following:
[mcumgr_debug.txt](https://github.com/apache/mynewt-mcumgr-cli/files/5423036/mcumgr_debug.txt)

It seems to be related with TxRxMgmtAsync, looking at `mynewt.apache.org/newtmgr/nmxact/udp/udp_sesn.go`, the function seems to always return "unsupported" (I don't know anything about Go, I just had a naive look at the code).

Is there any way to get udp connection working, maybe download an older version of mcumgr ? If so, how ? I did not see any release of mynewt-mcumgr-cli or how to specify the package version when doing a `go get`

Thanks.
Nicolas.

**Comment by jensschroer** [comment]
Hi, just to add to this ticket. I am experiencing the same issue but targeted towards the NXP frdm-k64f board.
I checked with tcpdump for any UDP messages going out, but no messages are sent to the board at all.

Thank you.
Jens

**Comment by nkaje** [comment]
@nicovince @jensschroer could you please try https://github.com/apache/mynewt-newtmgr/pull/176 and see if that fixes your issue?

**Comment by jensschroer** [comment]
@nkaje Thank you for the update. As I am not familiar with go, how would go about testing this the best way?

**Comment by nkaje** [comment]
You will have to rebuild mcumgr. Instructions to build is in https://github.com/apache/mynewt-mcumgr-cli/blob/master/README.md.

You need to make the following changes to your go.mod before building.

```
diff --git a/go.mod b/go.mod
index 730f94b..627bdf3 100644
--- a/go.mod
+++ b/go.mod
@@ -6,3 +6,5 @@ require (
        mynewt.apache.org/newt v0.0.0-20190805215728-4e771ee138aa
        mynewt.apache.org/newtmgr v0.0.0-20190909210301-5029f07bf173
 )
+
+replace mynewt.apache.org => github.com/nkaje/mynewt-newtmgr v0.0.0-20201026120808-84739773a36c
```
and follow the build steps.
This builds a new `mcumgr` binary.

**Comment by nicovince** [comment]
That worked for me, thanks ! 
Managed to upload a new image and confirm it on the device using mcumgr.

**Comment by jensschroer** [comment]
Thank you @nkaje . Will you update this repo with the latest dependency of newtmgr?

**Comment by nkaje** [comment]
I have created a PR https://github.com/apache/mynewt-mcumgr-cli/pull/18 for that here.
