### ISSUE TITLE
go get fails on Windows

### ISSUE THREAD

**Issue by rerickson1** [apache/mynewt-mcumgr-cli#19]
Using `go get` on Windows fails to compile and install.
```
C:\Users\ryan.erickson>go get github.com/apache/mynewt-mcumgr-cli/mcumgr
# mynewt.apache.org/newtmgr/newtmgr/bll
go\src\mynewt.apache.org\newtmgr\newtmgr\bll\bll_sesn_cfg_windows.go:35:15: undefined: nmcoap.MsgFilter
go\src\mynewt.apache.org\newtmgr\newtmgr\bll\bll_sesn_cfg_windows.go:36:15: undefined: nmcoap.MsgFilter
```
If I manually build and install it works fine:
```
cd C:\Users\ryan.erickson\go\src\github.com\apache\mynewt-mcumgr-cli\mcumgr
go build
go install
```

**Comment by nkaje** [comment]
Thanks @rerickson1 for reporting this.
I have uploaded a potential fix here
https://github.com/apache/mynewt-newtmgr/pull/177

Could you please try if this works for you? I don't have a windows setup, hence your help to test it here is appreciated.

**Comment by rerickson1** [comment]
Thanks for the fast response. I made that change locally and can confirm it fixes the issue.

**Comment by rerickson1** [comment]
Fix was merged.
