### ISSUE TITLE
Can't run mcumgr command on Windows 11

### ISSUE THREAD

**Issue by snowuyl** [apache/mynewt-mcumgr-cli#33]
mcumgr --conntype ble --connstring peer_name="Test SMP Server" echo hello
Error: Not Supported on Windows

**Comment by sjanc** [comment]
unfortunately Bluetooth transport is not supported on Windows

**Comment by snowuyl** [comment]
Thanks for your reply! Which connecting types supported on Windows 11?

**Comment by sjanc** [comment]
this should help
https://mynewt.apache.org/latest/newtmgr/command_list/newtmgr_conn.html

**Comment by snowuyl** [comment]
Thanks for your great support!
