### ISSUE TITLE
Does mcumgr command line tool support connecting type JLINK?

### ISSUE THREAD

**Issue by snowuyl** [apache/mynewt-mcumgr-cli#34]
I would like to use mcumgr command line tool with JLINK. Does mcumgr command line tool support connecting type JLINK?

**Comment by sjanc** [comment]
Hi,

No, JLINK is not supported (and probably never will cause if you have JLINK access you don't really need mcumgr)

**Comment by snowuyl** [comment]
Thanks for your reply!
