### ISSUE TITLE
Connecting with BLE address

### ISSUE THREAD

**Issue by attdona** [apache/mynewt-mcumgr-cli#7]
On my linux machine I'm not able to connect using BLE address instead of advertising name.

    mcumgr --conntype ble --connstring peer_name=Zephyr echo hello

works, but:

    mcumgr --conntype ble --connstring peer_id=C4:AE:3F:CA:04:1A echo hello

gives `Error: Failed to connect to peer after 10s`

**Comment by attdona** [comment]
I've found the problem: the BLE address must be lowercase:

    peer_id=c4:ae:3f:ca:04:1a

**Comment by caco3** [comment]
This should be treated as a bug!

**Comment by andib78** [comment]
it took me .. days !!!
it's currently unsolved .. or?
